name: example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  calendar_view:
    path: ../
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:
  build_runner: ^2.0.6
  build_web_compilers: ^3.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/