analyzer:
  exclude:
    - example/build/**
    - exmaple/android/**
    - example/ios/**
    - example/web/**
    - idea/**
    - .dart_tool/**
    - example/.dart_tool/**

linter:
  rules:
    lines_longer_than_80_chars: true
    avoid_print: true
    always_declare_return_types: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    use_function_type_syntax_for_parameters: true
    unnecessary_new: true
    unnecessary_brace_in_string_interps: true
    unnecessary_this: true
    avoid_bool_literals_in_conditional_expressions: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_null_checks: true
    unnecessary_null_aware_assignments: true
    unrelated_type_equality_checks: true
    unnecessary_statements: true
    throw_in_finally: true
    test_types_in_equals: true
    prefer_void_to_null: true
    prefer_relative_imports: true
    no_logic_in_create_state: true
    no_duplicate_case_values: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_type_to_string: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    empty_statements: true
    empty_constructor_bodies: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    always_require_non_null_named_parameters: true
    omit_local_variable_types: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    deprecated_consistency: true
    provide_deprecation_message: true
    directives_ordering: true
    exhaustive_cases: true
    file_names: true
    library_names: true
    library_prefixes: true
    no_default_cases: true
    no_runtimeType_toString: true
    non_constant_identifier_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors_in_immutables: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_full_hex_values_for_flutter_colors: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_rethrow_when_possible: true
    use_key_in_widget_constructors: false